version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - backend

  django:
    build:
      context: ./Django-Backend
    container_name: django
    command: gunicorn djangoBackend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./Django-Backend:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend
      - frontend 

  nextjs:
    build:
      context: ./NextJS-Frontend
    container_name: nextjs
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - django
    networks:
      - frontend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8010:80"
    volumes:
      - ./nginx.conf:/etc/nginx:ro
      - static_volume:/staticfiles
    depends_on:
      - django
      - nextjs
    networks:
      - frontend
      - backend

volumes:
  postgres_data:
  static_volume:

networks:
  backend:
  frontend:
