# Generated by Django 5.2.1 on 2025-06-21 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_type', models.CharField(max_length=50)),
                ('isWallet', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isDefault', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('wallet_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('In', 'Income'), ('Ex', 'Expense')], default='Ex', max_length=2)),
                ('name', models.CharField(choices=[('Salary', 'Salary'), ('Investments', 'Investments'), ('Freelance', 'Freelance'), ('Others', 'Others'), ('Food', 'Food'), ('Housing', 'Housing'), ('Groceries', 'Groceries'), ('Electronics', 'Electronics'), ('Transportation', 'Transportation'), ('Dining', 'Dining'), ('Healthcare', 'Healthcare'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=20, unique=True)),
            ],
            options={
                'db_table': 'master_category',
                'ordering': ['transaction_type', 'name'],
                'unique_together': {('transaction_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('In', 'INCOME'), ('Ex', 'EXPENSE')], default='Ex', max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField()),
                ('receiptPath', models.CharField(blank=True, max_length=255)),
                ('isRecurring', models.BooleanField(default=False)),
                ('recurringInterval', models.CharField(blank=True, max_length=50)),
                ('nextRecurringDate', models.DateTimeField(blank=True, null=True)),
                ('lastProcessedDate', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fintrack_app.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='fintrack_app.mastercategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('master_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_categories', to='fintrack_app.mastercategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'category',
                'ordering': ['master_category__transaction_type', 'master_category__name'],
                'unique_together': {('user', 'master_category')},
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_exceed', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('last_reset', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='fintrack_app.usercategory')),
            ],
            options={
                'db_table': 'budget',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('prompt_payload', models.JSONField()),
                ('llm_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('user', 'period_start', 'period_end')},
            },
        ),
    ]
