"""
Django settings for djangoBackend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import ssl
import certifi
import dj_database_url
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

ssl_context = ssl.create_default_context(cafile=certifi.where())

from celery.schedules import crontab

# import ssl
# ssl._create_default_https_context = ssl._create_unverified_context



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL  = "/media/"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-^qfmmcg5vkh0tg#d#cd@*$9qfn2o$f@7t)9m!so*@$8ec((c!*')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,.railway.app,.vercel.app').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'fintrack_app',

    'rest_framework.authtoken',
    'dj_rest_auth',

    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth.registration',

    'anymail',

    'django_celery_beat',
    'corsheaders',

]



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',
    'fintrack_app.middleware.CSRFExemptMiddleware',  # Exempt API endpoints from CSRF
]

# CORS settings for production
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,https://localhost:3000,https://*.vercel.app,https://*.railway.app').split(',')

CORS_ALLOW_CREDENTIALS = True

# Additional CORS settings for development
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'djangoBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoBackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL on Railway, fallback to SQLite for local development
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True  # Keep this True to enable timezone-aware datetimes



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Whitenoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTH_USER_MODEL='fintrack_app.User'
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # very important

# ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

# ACCOUNT_LOGIN_METHODS = {'email'}


# ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_AUTHENTICATION_METHOD = 'email'

# ACCOUNT_EMAIL_VERIFICATION = 'none'  # Use 'mandatory' in production


REST_FRAMEWORK = {
    'DEFAULT_PERMISSON_CLASSES':[
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES':[
        'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',  # Uncomment if using token authenticatione
    ]
   
}

# REST_AUTH_REGISTER_SERIALIZERS = {
#     'REGISTER_SERIALIZER': 'fintrack_app.serializers.register.CustomRegisterSerializer',
# }
# REST_AUTH_SERIALIZERS = {
#     'LOGIN_SERIALIZER': 'fintrack_app.serializers.register.CustomLoginSerializer',
# }

# EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
# DEFAULT_FROM_EMAIL='FinTrack Alerts <8fba6b001@smtp-brevo.com>'
# EMAIL_HOST='smtp-relay.brevo.com'
# EMAIL_PORT= 587
# EMAIL_USE_TLS= True
# EMAIL_HOST_USER='8fba6b001@smtp-brevo.com'

# EMAIL_HOST_PASSWORD='***REMOVED***'

# EMAIL_BACKEND='anymail.backends.brevo.EmailBackend'
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'anymail.backends.sendgrid.EmailBackend')

ANYMAIL = {
    "SENDGRID_API_KEY": os.getenv('SENDGRID_API_KEY', ''),
}

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'quester561@gmail.com')







# # EMAIL_BACKEND='anymail.backends.smtp.EmailBackend'
# ANYMAIL={
#     'BREVO_API_KEY':'***REMOVED***'
#     # 'BREVO_API_KEY':'***REMOVED***'
# }
# # DEFAULT_FROM_EMAIL='quester561@gmail.com'
# DEFAULT_FROM_EMAIL='FinTrack Alerts <8fba6b001@smtp-brevo.com>'


SITE_ID=1

# Celery Settings
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')  # Add this
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'  # Add this
# CELERY_TIMEZONE = 'UTC'  # Match your Django timezone
CELERY_TIMEZONE = 'Asia/Kathmandu'





# Celery Beat Schedule
CELERY_BEAT_SCHEDULE = {
    'reset-budgets-everyday': {
        'task': 'reset_monthly_budgets',  # Match the task name from @shared_task
        'schedule': crontab(minute='0', hour='0'),  # Midnight every day
        'schedule': crontab(minute='*'), #every minute 
        'options': {
            'expires': 50,  # Task expires after 1 hour
        }
    },
}