"""
Django settings for djangoBackend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import ssl
import certifi
ssl_context = ssl.create_default_context(cafile=certifi.where())

# import ssl
# ssl._create_default_https_context = ssl._create_unverified_context



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^qfmmcg5vkh0tg#d#cd@*$9qfn2o$f@7t)9m!so*@$8ec((c!*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'fintrack_app',

    'rest_framework.authtoken',
    'dj_rest_auth',

    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth.registration',

    'anymail'
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'djangoBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoBackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': 'os.getenv("POSTGRES_DB")',
#         'USER':os.getenv("POSTGRES_USER"),
#         'PASSWORD':os.getenv("POSTGRES_PASSWORD"),
#         'HOST':'db',
#         'PORT': '5432',

#     }
# }
DATABASES = {
    #for now sqlite3 is used
    'default':{
        'ENGINE':'django.db.backends.sqlite3',
        'NAME':BASE_DIR / 'db.sqlite3',
        
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTH_USER_MODEL='fintrack_app.User'
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # very important

# ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

# ACCOUNT_LOGIN_METHODS = {'email'}


# ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_AUTHENTICATION_METHOD = 'email'

# ACCOUNT_EMAIL_VERIFICATION = 'none'  # Use 'mandatory' in production


REST_FRAMEWORK = {
    'DEFAULT_PERMISSON_CLASSES':[
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES':[
        'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',  # Uncomment if using token authenticatione
    ]
   
}

# REST_AUTH_REGISTER_SERIALIZERS = {
#     'REGISTER_SERIALIZER': 'fintrack_app.serializers.register.CustomRegisterSerializer',
# }
# REST_AUTH_SERIALIZERS = {
#     'LOGIN_SERIALIZER': 'fintrack_app.serializers.register.CustomLoginSerializer',
# }

# EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
# DEFAULT_FROM_EMAIL='FinTrack Alerts <8fba6b001@smtp-brevo.com>'
# EMAIL_HOST='smtp-relay.brevo.com'
# EMAIL_PORT= 587
# EMAIL_USE_TLS= True
# EMAIL_HOST_USER='8fba6b001@smtp-brevo.com'

# EMAIL_HOST_PASSWORD='***REMOVED***'

# EMAIL_BACKEND='anymail.backends.brevo.EmailBackend'
EMAIL_BACKEND='anymail.backends.sendgrid.EmailBackend'

ANYMAIL={
    "SENDGRID_API_KEY":"***REMOVED***",
}

DEFAULT_FROM_EMAIL="quester561@gmail.com"







# # EMAIL_BACKEND='anymail.backends.smtp.EmailBackend'
# ANYMAIL={
#     'BREVO_API_KEY':'***REMOVED***'
#     # 'BREVO_API_KEY':'***REMOVED***'
# }
# # DEFAULT_FROM_EMAIL='quester561@gmail.com'
# DEFAULT_FROM_EMAIL='FinTrack Alerts <8fba6b001@smtp-brevo.com>'


SITE_ID=1

