# Generated by Django 5.2.1 on 2025-06-21 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0003_budget_unique_budget_per_user_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='updatedAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='createdAt',
            new_name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'name')},
        ),
        migrations.AddField(
            model_name='account',
            name='institution',
            field=models.CharField(blank=True, help_text='Optional financial institution name.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, help_text='Optional account number (if applicable).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CK', 'Checking'), ('SV', 'Savings'), ('CR', 'Credit Card'), ('CA', 'Cash'), ('IN', 'Investment')], help_text='Select the type of account.', max_length=2),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current balance of the account.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(help_text='A friendly name for this account (e.g. “Main Checking”).', max_length=100),
        ),
        migrations.RemoveField(
            model_name='account',
            name='isDefault',
        ),
        migrations.RemoveField(
            model_name='account',
            name='isWallet',
        ),
        migrations.RemoveField(
            model_name='account',
            name='wallet_number',
        ),
    ]
