# Generated by Django 5.2.1 on 2025-06-09 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_type', models.CharField(max_length=50, unique=True)),
                ('isWallet', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isDefault', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('wallet_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'account',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('In', 'INCOME'), ('Ex', 'EXPENSE')], default='Ex')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('receiptUrl', models.URLField(blank=True)),
                ('isRecurring', models.BooleanField(default=False)),
                ('recurringInterval', models.CharField(blank=True, max_length=50)),
                ('nextRecurringDate', models.DateTimeField(blank=True, null=True)),
                ('lastProcessedDate', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fintrack_app.account')),
            ],
            options={
                'db_table': 'transaction',
                'ordering': ['-date'],
                'unique_together': {('account', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='fintrack_app.transaction')),
            ],
            options={
                'db_table': 'budget',
                'ordering': ['-createdAt'],
            },
        ),
    ]
