# Generated by Django 5.2.1 on 2025-06-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0004_budget_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
