# Generated by Django 5.2.1 on 2025-06-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0008_alter_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='updatedAt',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
