# Generated by Django 5.2.1 on 2025-06-11 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0011_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
    ]
