# Generated by Django 5.2.1 on 2025-06-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0012_alter_transaction_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(max_length=50),
        ),
    ]
