# Generated by Django 5.2.1 on 2025-06-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0014_alter_account_user_alter_budget_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorytotal',
            unique_together=set(),
        ),
    ]
