# Generated by Django 5.2.1 on 2025-06-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0017_alter_category_user_alter_transaction_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='amount',
            new_name='budget_amount',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='updatedAt',
        ),
    ]
