# Generated by Django 5.2.1 on 2025-06-16 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0018_rename_amount_budget_budget_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='transaction',
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='fintrack_app.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='is_exceed',
            field=models.BooleanField(default=False),
        ),
    ]
