# Generated by Django 5.2.1 on 2025-06-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0019_remove_budget_transaction_budget_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='last_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
