# Generated by Django 5.2.1 on 2025-06-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0021_monthlyinsight'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyinsight',
            unique_together=set(),
        ),
    ]
