# Generated by Django 5.2.1 on 2025-06-18 12:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0022_alter_monthlyinsight_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyinsight',
            unique_together={('user', 'period_start', 'period_end')},
        ),
    ]
