# Generated by Django 5.2.1 on 2025-06-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0023_alter_monthlyinsight_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receiptUrl',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.CharField(blank=True),
        ),
    ]
