# Generated by Django 5.2.1 on 2025-06-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0024_remove_transaction_receipturl_transaction_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='receipt',
            new_name='receiptPath',
        ),
    ]
