# Generated by Django 5.2.1 on 2025-06-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0025_rename_receipt_transaction_receiptpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('investment', 'Investment'), ('others', 'Others')], default='salary'),
        ),
    ]
