# Generated by Django 5.2.1 on 2025-06-20 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0026_alter_category_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['transaction_type', 'category']},
        ),
        migrations.AddField(
            model_name='category',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='INCOME', max_length=7),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Investments', 'Investments'), ('Freelance', 'Freelance'), ('Others', 'Others'), ('Food', 'Food'), ('Housing', 'Housing'), ('Groceries', 'Groceries'), ('Electronics', 'Electronics'), ('Transportation', 'Transportation'), ('Dining', 'Dining'), ('Healthcare', 'Healthcare'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'transaction_type', 'category')},
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
