# Generated by Django 5.2.1 on 2025-06-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0027_alter_category_options_category_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Investments', 'Investments'), ('Freelance', 'Freelance'), ('Others', 'Others'), ('Food', 'Food'), ('Housing', 'Housing'), ('Groceries', 'Groceries'), ('Electronics', 'Electronics'), ('Transportation', 'Transportation'), ('Dining', 'Dining'), ('Healthcare', 'Healthcare'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiptPath',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('In', 'INCOME'), ('Ex', 'EXPENSE')], default='Ex', max_length=2),
        ),
    ]
