# Generated by Django 5.2.1 on 2025-06-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_app', '0028_alter_transaction_category_alter_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='transaction_type',
            field=models.CharField(choices=[('In', 'Income'), ('Ex', 'Expense')], default='Ex', max_length=7),
        ),
    ]
